Repository ProctorU/storm, pull requests merged in 2018-10, with the labels that each got.

#183 Bump Hootstrap to 0.7.0
  Gemfile
  Gemfile.lock
Labels: Dependency: Gems

#187 Utilize Hootstrap's page-actions pattern
  app/views/devise/invitations/new.html.erb
  app/views/tokens/index.html.erb
  app/views/tokens/new.html.erb
  app/views/users/index.html.erb
  app/views/users/invitations/instructions/index.html.erb
  app/views/users/passwords/instructions/index.html.erb
  app/views/websites/charts/response_time/index.html.erb
  app/views/websites/edit.html.erb
  app/views/websites/index.html.erb
  app/views/websites/new.html.erb
  app/views/websites/show.html.erb
  config/locales/en.yml
Labels: Status: Reviewed, Type: Technical Debt

#166 Rails 5.2 upgrade
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/controllers/application_controller.rb
  app/views/layouts/application.html.erb
  bin/bundle
  bin/setup
  bin/update
  bin/yarn
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/spring.rb
  test/test_helper.rb
Labels: Status: Reviewed, Type: Feature, Type: Technical Debt

#189 Eager load pings
  app/controllers/websites_controller.rb
Labels: Status: Review Complete, Type: Technical Debt
