Repository ProctorU/storm, pull requests merged in 2018-07, with the labels that each got.

#155 Bump Hootstrap to 0.4.0
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/reboot/_base.scss
Labels: Status: Reviewed, Type: Technical Debt

#156 Remove Paranoia gem
  Gemfile
  Gemfile.lock
  app/controllers/users/invitations_controller.rb
  app/models/ping.rb
  app/models/user.rb
  app/models/website.rb
  db/migrate/20180713023802_remove_deleted_at_from_tables.rb
  db/schema.rb
  test/controllers/users/invitations_controller_test.rb
  test/controllers/users_controller_test.rb
Labels: Type: Database, Type: Technical Debt

#157 Revert "Remove Paranoia gem"
  Gemfile
  Gemfile.lock
  app/controllers/users/invitations_controller.rb
  app/models/ping.rb
  app/models/user.rb
  app/models/website.rb
  db/migrate/20180713023802_remove_deleted_at_from_tables.rb
  db/schema.rb
  test/controllers/users/invitations_controller_test.rb
  test/controllers/users_controller_test.rb
Labels: Type: Bug, Type: Database

#158 Remove Paranoia gem
  Gemfile
  Gemfile.lock
  app/controllers/users/invitations_controller.rb
  app/models/ping.rb
  app/models/user.rb
  app/models/website.rb
  db/migrate/20180713023802_remove_deleted_at_from_tables.rb
  db/schema.rb
  test/controllers/users/invitations_controller_test.rb
  test/controllers/users_controller_test.rb
Labels: Type: Database, Type: Technical Debt

#159 Use delete_all to destroy pings
  app/models/website.rb
Labels: Status: Reviewed, Type: Feature, Type: Technical Debt

#160 Improve page performance on websites#show
  app/controllers/websites_controller.rb
  app/models/website.rb
Labels: Status: Review Complete, Type: Technical Debt

#161 Redesign homepage
  app/assets/images/welcome/icon.png
  app/assets/images/welcome/mockup.png
  app/assets/stylesheets/utils/_base.scss
  app/assets/stylesheets/utils/_shadow.scss
  app/assets/stylesheets/views/_welcome.scss
  app/views/devise/sessions/new.html.erb
  app/views/layouts/unauthenticated.html.erb
  app/views/welcome/index.html.erb
  config/locales/en.yml
Labels: Status: Review Complete, Type: Design

#168 Fix mocha integration and upgrade mocha from v1.4.0 to v1.6.0
  Gemfile
  Gemfile.lock
  test/test_helper.rb
Labels: Status: Review Complete, Type: Bug
